# Generated by Django 5.1.1 on 2024-10-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('imagen', models.TextField()),
                ('precio_venta', models.IntegerField()),
                ('url_mercadolibre', models.TextField()),
            ],
        ),
    ]
