# Generated by Django 5.1.1 on 2024-10-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='usuario',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
