# Generated by Django 5.1.1 on 2024-10-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_articulo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='usuario',
            field=models.IntegerField(),
        ),
    ]
