# Generated by Django 5.1.1 on 2024-10-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('user', 'User')], max_length=10, null=True),
        ),
    ]
