# Generated by Django 5.1.1 on 2024-10-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('user', 'Usuario')], max_length=10, null=True),
        ),
    ]
