# Generated by Django 5.1.1 on 2024-10-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, choices=[('administrador', 'Administrador'), ('usuario', 'Usuario')], max_length=20, null=True),
        ),
    ]
